### ISSUE TITLE
user-story.md

### ISSUE THREAD

**Issue by MehulBheda** [ibm-developer-skills-network/aolwx-devops-capstone-template#16]
**As a** Revenue Product Owner 
**I need** Payment function
**So that** Customer can pay tax
      
### Details and Assumptions
    * Payments_Process.pdf     
### Acceptance Criteria     
    gherkin 
    Given Customer does payment with credit card
    When Amount is more than $100
    Then Deposit the amount to account

**Comment by rofrano** [comment]
Hi @MehulBheda , You probably ment for this to go to your fork not our upstream. :)

**Comment by MehulBheda** [comment]
Hi John,
My sincere apology for this. Thank you for highlighting the mistake.

Your in-depth knowledge and clear explanations on the topics were truly
impressive throughout the entire certification process.
Thank you for your invaluable guidance!


Kind regards,
Mehul
