### ISSUE TITLE
Create a CD Pipeline to Automate Deployment to Kubernetes

### ISSUE THREAD

**Issue by misha-philip** [ibm-developer-skills-network/aolwx-devops-capstone-template#19]
**As a** developer
**I need** to create a CD pipeline to automate deployment to Kubernetes
**So that** the developers are not wasting their time doing it manually

### Assumptions
* Use Tekton to define the pipeline
* It should clone, lint, test, build, and deploy the service
* Deployment should be to OpenShift
* It can use a manual trigger for this MVP

### Acceptance Criteria
Given the CD pipeline has been created
When I trigger the pipeline run
Then I should see the accounts service deployed to OpenShift

**Comment by rofrano** [comment]
Hi @misha-philip , I believe you meant to create this Story on your Fork not the Upstream repo.
