### ISSUE TITLE
New version of SQLAlchemy breaks models.py

### ISSUE THREAD

**Issue by bashgame** [ibm-developer-skills-network/aolwx-devops-capstone-template#3]
The latest version of SQLAlchemy (v2.0.0 released 1/26/23) is no longer compatible with the way the code is written. I get runtime errors saying that sqlalchemy has no attribute __all__. Modifying the requirements file to use v1.4.46 causes the code to run as expected. v1.4.46 was released 01/03/23 so it is less than a month old.
In the long term the init_db function will need to be changed to use the new 2.0 version for creating instances.

thanks,
Amen

**Comment by rofrano** [comment]
@bashgame Thank for reporting this. I have pinned SQLAlchemy to v1.4.46 in the `requirements.txt` file in this Pull Request #4 . All previously broken tests have passed so I'm making this closed.
